name: Build

on:
  push:
    branches:
      - main
#  pull_request:
#    types: [ready_for_review, synchronize]

env:
  PYTHON_VERSION: 3.8

jobs:
  build_mac:
    name: "MacOS Latest clang"
    runs-on: macos-latest
    steps:

    - name: Install prerequisites
      run: |
        brew install automake
        brew list

    - uses: actions/checkout@v4

    - name: Install libpng
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        bash macos/run_build_libpng12.sh $HOME
        pwd
        ls -la $HOME/povray_bundle

    - name: Install boost
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        bash macos/run_build_boost.sh $HOME
        pwd
        ls -la $HOME/povray_bundle

    - name: Build povray
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        bash macos/run_build_povray.sh $HOME
        pwd
        ls -la $HOME/povray_bundle

    # - name: Upload artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: dist-without-markdown
    #       path: |
    #         dist
    #         !dist/**/*.md
