name: Build and release

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  build_mac:
    name: "MacOS 12 intel clang"
    runs-on: macos-12
    steps:

    - name: Install prerequisites
      run: |
        brew install automake
        # brew list

    - uses: actions/checkout@v4

    - name: Install boost
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        bash macos/run_build_boost.sh $HOME
        pwd
        ls -la $HOME/povray_bundle/boost_1_76_static/lib

    - name: Install libpng
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        bash macos/run_build_libpng12.sh $HOME
        pwd
        ls -la $HOME/povray_bundle

    - name: Build povray
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        bash macos/run_build_povray.sh $HOME

    - name: Check build
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        ls -la $HOME/povray_bundle/bin
        otool -L $HOME/povray_bundle/bin/povray
        $HOME/povray_bundle/bin/povray -h

    - name: Create bundle
      shell: bash
      env:
        ARTIFACT_NAME: povray_${{ runner.os }}_${{ runner.arch }}.tar.bz2
      run: |
        OUTPUT_DIR=${GITHUB_WORKSPACE}/povray
        cd ${GITHUB_WORKSPACE}
        mkdir -p ${OUTPUT_DIR}/bin
        mkdir -p ${OUTPUT_DIR}/include
        ls -la $HOME/povray_bundle
        cp $HOME/povray_bundle/bin/* ${OUTPUT_DIR}/bin/
        cp $HOME/povray_bundle/share/povray-*/include/* ${OUTPUT_DIR}/include
        tar cjvf ${{ env.ARTIFACT_NAME }} povray
        ls -l ${{ env.ARTIFACT_NAME }}

    - name: Upload artifact
      env:
        ARTIFACT_NAME: povray_${{ runner.os }}_${{ runner.arch }}.tar.bz2
      uses: actions/upload-artifact@v4
      with:
        name: povray_bundle_macos_intel
        path: ${{ env.ARTIFACT_NAME }}

###############################################

  build_mac_arm64:
    name: "MacOS 14 arm64 clang"
    runs-on: macos-14
    steps:

    - name: Install prerequisites
      run: |
        brew install automake
        # brew list

    - uses: actions/checkout@v4

    - name: Install boost
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        bash macos/run_build_boost.sh $HOME
        pwd
        ls -la $HOME/povray_bundle/boost_1_76_static/lib

    - name: Install libpng
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        bash macos/run_build_libpng12.sh $HOME
        pwd
        ls -la $HOME/povray_bundle

    - name: Build povray
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        bash macos/run_build_povray.sh $HOME

    - name: Check build
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        ls -la $HOME/povray_bundle/bin
        otool -L $HOME/povray_bundle/bin/povray
        $HOME/povray_bundle/bin/povray -h

    - name: Create bundle
      shell: bash
      env:
        ARTIFACT_NAME: povray_${{ runner.os }}_${{ runner.arch }}.tar.bz2
      run: |
        OUTPUT_DIR=${GITHUB_WORKSPACE}/povray
        cd ${GITHUB_WORKSPACE}
        mkdir -p ${OUTPUT_DIR}/bin
        mkdir -p ${OUTPUT_DIR}/include
        ls -la $HOME/povray_bundle
        cp $HOME/povray_bundle/bin/* ${OUTPUT_DIR}/bin/
        cp $HOME/povray_bundle/share/povray-*/include/* ${OUTPUT_DIR}/include
        tar cjvf ${{ env.ARTIFACT_NAME }} povray
        ls -l ${{ env.ARTIFACT_NAME }}

    - name: Upload artifact
      env:
        ARTIFACT_NAME: povray_${{ runner.os }}_${{ runner.arch }}.tar.bz2
      uses: actions/upload-artifact@v4
      with:
        name: povray_bundle_macos_arm64
        path: ${{ env.ARTIFACT_NAME }}

###############################################

  build_linux_x64:
    name: "Linux intel gcc"
    runs-on: ubuntu-22.04
    steps:

    - name: Install prerequisites
      run: |
        which automake
        automake --version

    - uses: actions/checkout@v4

    - name: Install boost
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        bash linux/run_build_boost.sh $HOME
        pwd
        ls -la $HOME/povray_bundle/boost_1_76_static/lib

    - name: Install libpng
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        bash linux/run_build_libpng12.sh $HOME
        pwd
        ls -la $HOME/povray_bundle

    - name: Build povray
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        bash linux/run_build_povray.sh $HOME

    - name: Check build
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        ls -la $HOME/povray_bundle/bin
        ldd $HOME/povray_bundle/bin/povray
        $HOME/povray_bundle/bin/povray -h

    - name: Create bundle
      shell: bash
      env:
        ARTIFACT_NAME: povray_${{ runner.os }}_${{ runner.arch }}.tar.bz2
      run: |
        OUTPUT_DIR=${GITHUB_WORKSPACE}/povray
        cd ${GITHUB_WORKSPACE}
        mkdir -p ${OUTPUT_DIR}/bin
        mkdir -p ${OUTPUT_DIR}/include
        ls -la $HOME/povray_bundle
        cp $HOME/povray_bundle/bin/* ${OUTPUT_DIR}/bin/
        cp $HOME/povray_bundle/share/povray-*/include/* ${OUTPUT_DIR}/include
        tar cjvf ${{ env.ARTIFACT_NAME }} povray
        ls -l ${{ env.ARTIFACT_NAME }}

    - name: Upload artifact
      env:
        ARTIFACT_NAME: povray_${{ runner.os }}_${{ runner.arch }}.tar.bz2
      uses: actions/upload-artifact@v4
      with:
        name: povray_bundle_linux_x64
        path: ${{ env.ARTIFACT_NAME }}

###############################################

  build_win_x64:
    name: "Windows intel msvc"
    runs-on: windows-2019

    steps:
    - name: Install prerequisite
      run: |
        choco install -r wget

    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build povray
      shell: pwsh
      run: |
        powershell -NoProfile -ExecutionPolicy Unrestricted ./windows/run_build_povray.ps1 $env:TEMP $env:GITHUB_WORKSPACE

    - name: Create bundle
      shell: bash
      env:
        ARTIFACT_NAME: povray_${{ runner.os }}_${{ runner.arch }}.tar.bz2
      run: |
        tar cjvf ${{ env.ARTIFACT_NAME }} povray

    - name: Upload artifact
      env:
        ARTIFACT_NAME: povray_${{ runner.os }}_${{ runner.arch }}.tar.bz2
      uses: actions/upload-artifact@v4
      with:
        name: povray_bundle_win_x64
        path: ${{ env.ARTIFACT_NAME }}


###############################################

  release_build:
    needs: [build_mac,build_mac_arm64,build_linux_intel,build_win_x64]
    runs-on: ubuntu-latest
    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        merge-multiple: true
    - run: |
        ls -lR

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: artifacts/*.tar.bz2
