name: Build and release

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

#  pull_request:
#    types: [ready_for_review, synchronize]

jobs:
  build_mac:
    name: "MacOS 12 intel clang"
    runs-on: macos-12
    steps:

    - name: Install prerequisites
      run: |
        brew install automake
        # brew list

    - uses: actions/checkout@v4

    - name: Install boost
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        bash macos/run_build_boost.sh $HOME
        pwd
        ls -la $HOME/povray_bundle/boost_1_76_static/lib

    - name: Install libpng
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        bash macos/run_build_libpng12.sh $HOME
        pwd
        ls -la $HOME/povray_bundle

    - name: Build povray
      shell: bash
      run: |
        OUTPUT_DIR=${GITHUB_WORKSPACE}/povray
        cd ${GITHUB_WORKSPACE}
        bash macos/run_build_povray.sh $HOME
        mkdir -p ${OUTPUT_DIR}/bin
        mkdir -p ${OUTPUT_DIR}/include
        ls -la $HOME/povray_bundle
        cp -v $HOME/povray_bundle/bin/* ${OUTPUT_DIR}/bin/
        cp -v $HOME/povray_bundle/share/povray-*/include/* ${OUTPUT_DIR}/include
        tar cjf povray_bundle.tar.bz2 povray

    - name: Check build
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        ls -la $HOME/povray_bundle/bin
        otool -L $HOME/povray_bundle/bin/povray
        $HOME/povray_bundle/bin/povray -h

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: povray_bundle_macos_intel
        path: |
          povray_bundle.tar.bz2

###############################################

  build_mac_arm64:
    name: "MacOS 14 arm64 clang"
    runs-on: macos-14
    steps:

    - name: Install prerequisites
      run: |
        brew install automake
        # brew list

    - uses: actions/checkout@v4

    - name: Install boost
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        bash macos/run_build_boost.sh $HOME
        pwd
        ls -la $HOME/povray_bundle/boost_1_76_static/lib

    - name: Install libpng
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        bash macos/run_build_libpng12.sh $HOME
        pwd
        ls -la $HOME/povray_bundle

    - name: Build povray
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        bash macos/run_build_povray.sh $HOME
        pwd
        ls -la $HOME/povray_bundle
        cp -r $HOME/povray_bundle ${GITHUB_WORKSPACE}

    - name: Check build
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        ls -la $HOME/povray_bundle/bin
        otool -L $HOME/povray_bundle/bin/povray
        $HOME/povray_bundle/bin/povray -h

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: povray_bundle_macos_arm64
        path: |
          povray_bundle/bin
          povray_bundle/share

###############################################

  build_linux_intel:
    name: "Linux intel gcc"
    runs-on: ubuntu-22.04
    steps:

    - name: Install prerequisites
      run: |
        which automake
        # brew list

    - uses: actions/checkout@v4

    - name: Install boost
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        bash linux/run_build_boost.sh $HOME
        pwd
        ls -la $HOME/povray_bundle/boost_1_76_static/lib

    - name: Install libpng
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        bash linux/run_build_libpng12.sh $HOME
        pwd
        ls -la $HOME/povray_bundle

    - name: Build povray
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        bash linux/run_build_povray.sh $HOME
        pwd
        ls -la $HOME/povray_bundle
        cp -r $HOME/povray_bundle ${GITHUB_WORKSPACE}

    - name: Check build
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}
        ls -la $HOME/povray_bundle/bin
        ldd $HOME/povray_bundle/bin/povray
        $HOME/povray_bundle/bin/povray -h

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: povray_bundle_linux_intel
        path: |
          povray_bundle/bin
          povray_bundle/share

###############################################

