name: Build and release

on:
  push:
    branches:
      - main

jobs:
  build_win_intel:
    name: "Windows intel msvc"
    runs-on: windows-latest

    steps:
    - name: Install prerequisite
      run: |
        choco install -r wget

    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build povray
      shell: pwsh
      run: |
        Get-ChildItem env:
        powershell -NoProfile -ExecutionPolicy Unrestricted ./windows/run_build_povray.ps1
        # msbuild project\HelloWorld\HelloWorld\HelloWorld.vcxproj -t:rebuild -verbosity:diag -property:Configuration=Release


