name: Release test 1

on:
  push:
    branches:
      - main

jobs:
  build_linux_intel:
    name: "Linux intel gcc"
    runs-on: ubuntu-22.04
    steps:
    - name: Create file
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}

        mkdir test_dir
        echo "XXX" > test_dir/test_file
        chmod +x test_dir/test_file
        tar cjvf my_files.tar.bz2 test_dir
        ls -alR

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: test_file_linux_intel
        path: |
          my_files.tar.bz2

  release_linux_intel:
    needs: build_linux_intel
    runs-on: ubuntu-latest
    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        name: my-artifact
    - run: ls -lR
