name: Release test 1

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  build_linux_intel:
    name: "Linux intel gcc"
    runs-on: ubuntu-22.04
    steps:
    - name: Create file
      env:
        ARTIFACT_NAME: my_files_${{ runner.os }}_${{ runner.arch }}.tar.bz2
      shell: bash
      run: |
        echo ARTIFACT_NAME: ${{ env.ARTIFACT_NAME }}

        cd ${GITHUB_WORKSPACE}
        mkdir test_dir
        echo "XXX" > test_dir/test_file
        chmod +x test_dir/test_file
        tar cjf ${{ env.ARTIFACT_NAME }} test_dir
        ls -alR

    - name: Upload artifact
      env:
        ARTIFACT_NAME: my_files_${{ runner.os }}_${{ runner.arch }}.tar.bz2
      uses: actions/upload-artifact@v4
      with:
        name: test_file_linux_intel
        path: |
          ${{ env.ARTIFACT_NAME }}

  build_macos_arm64:
    name: "MacOS arm64 clang"
    runs-on: macos-14
    steps:
    - name: Create file
      env:
        ARTIFACT_NAME: my_files_${{ runner.os }}_${{ runner.arch }}.tar.bz2
      shell: bash
      run: |
        echo ARTIFACT_NAME: ${{ env.ARTIFACT_NAME }}

        cd ${GITHUB_WORKSPACE}
        mkdir test_dir
        echo "YYY" > test_dir/test_file
        chmod +x test_dir/test_file
        tar cjf ${{ env.ARTIFACT_NAME }} test_dir
        ls -alR

    - name: Upload artifact
      env:
        ARTIFACT_NAME: my_files_${{ runner.os }}_${{ runner.arch }}.tar.bz2
      uses: actions/upload-artifact@v4
      with:
        name: test_file_macos_arm64
        path: |
          ${{ env.ARTIFACT_NAME }}

  release_all:
    needs: [build_linux_intel,build_macos_arm64]
    runs-on: ubuntu-latest
    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        merge-multiple: true
    - run: |
        ls -lR

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: artifacts/*.tar.bz2
